GRANT ALL_PRIVILEGES ON CATALOG `ab_dev_catalog` TO `kavi.sathish@avatest.in`;
GRANT ALL_PRIVILEGES, APPLY_TAG, BROWSE, MANAGE, MODIFY, READ_VOLUME, REFRESH, SELECT, USE_CATALOG, USE_SCHEMA, WRITE_VOLUME ON CATALOG `ab_dev_catalog` TO `deeraj.rajeev@avatest.in`;
GRANT ALL_PRIVILEGES, USE_CATALOG, USE_SCHEMA ON CATALOG `ab_dev_catalog` TO `naveenap@avatest.in`;
GRANT USE_SCHEMA ON CATALOG `ab_dev_catalog` TO `dharun@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON CATALOG `ab_dev_catalog` TO `pandi.anbu@avatest.in`;
GRANT APPLY_TAG, BROWSE, CREATE_FUNCTION, CREATE_MATERIALIZED_VIEW, CREATE_MODEL, CREATE_SCHEMA, CREATE_TABLE, CREATE_VOLUME, MODIFY, READ_VOLUME, SELECT, USE_CATALOG, USE_SCHEMA, WRITE_VOLUME ON CATALOG `ab_dev_catalog` TO `ABankCheck`;
GRANT ALL_PRIVILEGES ON CATALOG `ab_dev_catalog` TO `chandru.ramesh@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON CATALOG `ab_dev_catalog` TO `vishnuprakash.subramanian@avatest.in`;
GRANT EXECUTE, READ_VOLUME, SELECT, USE_CATALOG, USE_SCHEMA ON CATALOG `ab_dev_catalog` TO `akanksh.adi@avatest.in`;
GRANT REFRESH ON CATALOG `ab_dev_catalog` TO `06203d42-0c1e-41c4-a393-3028001f3054`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON CATALOG `ab_dev_catalog` TO `vishnu@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE, USE_CATALOG, USE_SCHEMA ON CATALOG `ab_dev_catalog` TO `sabareeswaraks@avatest.in`;
GRANT ALL_PRIVILEGES, USE_CATALOG ON CATALOG `ab_dev_catalog` TO `vijayaramuprawin@avatest.in`;
GRANT USE_CATALOG ON CATALOG `ab_dev_catalog` TO `d889a460-f792-4926-8f4c-e52b42f4f6b7`;
GRANT USE_SCHEMA ON SCHEMA `ab_dev_catalog._data_classification` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog._data_classification.errors` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog._data_classification.results` TO `account users`;
GRANT USE_SCHEMA ON SCHEMA `ab_dev_catalog.bronze` TO `ABankCheck_France`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `ab_dev_catalog.bronze` TO `vijayaramuprawin@avatest.in`;
GRANT SELECT ON TABLE `ab_dev_catalog.bronze.covid` TO `ABankCheck_France`;
GRANT ALL_PRIVILEGES ON TABLE `ab_dev_catalog.bronze.coviddaily` TO `akaash.panneerselvam@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON TABLE `ab_dev_catalog.bronze.sampletest` TO `naveenap@avatest.in`;
GRANT SELECT ON TABLE `ab_dev_catalog.bronze.titanic_encrypted` TO `keyvault_user`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `ab_dev_catalog.config` TO `vijayaramuprawin@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON TABLE `ab_dev_catalog.crypto.key_vault` TO `naveenap@avatest.in`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `ab_dev_catalog.default` TO `vijayaramuprawin@avatest.in`;
GRANT SELECT, USE_SCHEMA ON SCHEMA `ab_dev_catalog.default` TO `d889a460-f792-4926-8f4c-e52b42f4f6b7`;
GRANT USE_SCHEMA ON SCHEMA `ab_dev_catalog.information_schema` TO `vijayaramuprawin@avatest.in`;
GRANT USE_SCHEMA ON SCHEMA `ab_dev_catalog.information_schema` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `ab_dev_catalog.information_schema.volumes` TO `account users`;
GRANT SELECT, USE_SCHEMA ON SCHEMA `ab_dev_catalog.masking` TO `sabareeswaraks@avatest.in`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `ab_dev_catalog.silver` TO `vijayaramuprawin@avatest.in`;
GRANT SELECT ON TABLE `ab_dev_catalog.silver.covid_masked` TO `naveenap@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON TABLE `ab_dev_catalog.silver.covid_masked` TO `dharun@avatest.in`;
GRANT ALL_PRIVILEGES, APPLY_TAG, BROWSE, CREATE_MATERIALIZED_VIEW, CREATE_SCHEMA, CREATE_TABLE, CREATE_VOLUME, EXECUTE, EXTERNAL_USE_SCHEMA, MANAGE, MODIFY, READ_VOLUME, REFRESH, SELECT, USE_CATALOG, USE_SCHEMA, WRITE_VOLUME ON CATALOG `bronze` TO `pandi.anbu@avatest.in`;
GRANT APPLY_TAG, BROWSE, CREATE_MATERIALIZED_VIEW, CREATE_SCHEMA, CREATE_TABLE, CREATE_VOLUME, EXECUTE, MODIFY, READ_VOLUME, REFRESH, SELECT, USE_CATALOG, USE_SCHEMA, WRITE_VOLUME ON CATALOG `bronze` TO `sujeeth.gnanasekaran@avatest.in`;
GRANT ALL_PRIVILEGES ON CATALOG `bronze` TO `balakumaran.r@avatest.in`;
GRANT APPLY_TAG, BROWSE, CREATE_FUNCTION, CREATE_MATERIALIZED_VIEW, CREATE_MODEL, CREATE_SCHEMA, CREATE_TABLE, CREATE_VOLUME, MODIFY, READ_VOLUME, SELECT, USE_CATALOG, USE_SCHEMA, WRITE_VOLUME ON CATALOG `bronze` TO `shyam.sa@avatest.in`;
GRANT ALL_PRIVILEGES, USE_CATALOG ON CATALOG `bronze` TO `vijayaramuprawin@avatest.in`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `bronze.abank` TO `vijayaramuprawin@avatest.in`;
GRANT APPLY_TAG, EXECUTE, MODIFY, READ_VOLUME, REFRESH, SELECT, USE_SCHEMA ON SCHEMA `bronze.abank` TO `vishnuprakash.subramanian@avatest.in`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `bronze.buckeye_poc` TO `vijayaramuprawin@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON SCHEMA `bronze.buckeye_poc` TO `dharun@avatest.in`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `bronze.config` TO `vijayaramuprawin@avatest.in`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `bronze.dbo` TO `vijayaramuprawin@avatest.in`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `bronze.default` TO `vijayaramuprawin@avatest.in`;
GRANT USE_SCHEMA ON SCHEMA `bronze.information_schema` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `bronze.information_schema.volumes` TO `account users`;
GRANT ALL_PRIVILEGES, USE_SCHEMA ON SCHEMA `bronze.silver` TO `vijayaramuprawin@avatest.in`;
GRANT ALL_PRIVILEGES, BROWSE ON CATALOG `dw_nfi_catalog` TO `account users`;
GRANT USE_SCHEMA ON SCHEMA `dw_nfi_catalog.information_schema` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `dw_nfi_catalog.information_schema.volumes` TO `account users`;
GRANT APPLY_TAG, BROWSE, EXTERNAL_USE_SCHEMA, READ_VOLUME, REFRESH, SELECT, USE_CATALOG, USE_SCHEMA ON CATALOG `genetl` TO `account users`;
GRANT USE_SCHEMA ON SCHEMA `genetl.information_schema` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `genetl.information_schema.volumes` TO `account users`;
GRANT USE_CATALOG ON CATALOG `main` TO `account users`;
GRANT USE_SCHEMA ON SCHEMA `main.default` TO `account users`;
GRANT USE_SCHEMA ON SCHEMA `main.information_schema` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `main.information_schema.volumes` TO `account users`;
GRANT EXECUTE, SELECT, USE_CATALOG, USE_SCHEMA ON CATALOG `samples` TO `account users`;
GRANT USE_SCHEMA ON SCHEMA `samples.information_schema` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `samples.information_schema.volumes` TO `account users`;
GRANT BROWSE ON CATALOG `sap_dev_demo` TO `account users`;
GRANT ALL_PRIVILEGES, MANAGE ON CATALOG `sap_dev_demo` TO `pandi.anbu@avatest.in`;
GRANT USE_CATALOG ON CATALOG `sap_dev_demo` TO `49fdf1e9-1bb2-4206-93ea-b67754515c9a`;
GRANT ALL_PRIVILEGES, MANAGE ON CATALOG `sap_dev_demo` TO `balakumaran.r@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON CATALOG `sap_dev_demo` TO `harshavarthini@avatest.in`;
GRANT ALL_PRIVILEGES, EXECUTE, EXTERNAL_USE_SCHEMA, MANAGE, READ_VOLUME, SELECT, USE_CATALOG, USE_SCHEMA ON CATALOG `sap_dev_demo` TO `akanksh.adi@avatest.in`;
GRANT SELECT, USE_SCHEMA ON SCHEMA `sap_dev_demo.default` TO `49fdf1e9-1bb2-4206-93ea-b67754515c9a`;
GRANT USE_SCHEMA ON SCHEMA `sap_dev_demo.information_schema` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `sap_dev_demo.information_schema.volumes` TO `account users`;
GRANT USE_CATALOG ON CATALOG `sys` TO `naveenap@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON CATALOG `sys` TO `sabareeswaraks@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON CATALOG `sys` TO `shyam.sa@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON CATALOG `sys` TO `pandi.anbu@avatest.in`;
GRANT USE_SCHEMA ON SCHEMA `sys.crypto` TO `naveenap@avatest.in`;
GRANT SELECT ON TABLE `sys.default.titanic_encrypted` TO `keyvault_user`;
GRANT SELECT ON TABLE `sys.default.titanic_encrypted` TO `keyvault_user_1`;
GRANT USE_SCHEMA ON SCHEMA `sys.information_schema` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `sys.information_schema.volumes` TO `account users`;
GRANT BROWSE ON CATALOG `test_catalog` TO `account users`;
GRANT APPLY_TAG, BROWSE, CREATE_FUNCTION, CREATE_SCHEMA, CREATE_TABLE, EXECUTE, MODIFY, READ_VOLUME, REFRESH, SELECT, USE_CATALOG, USE_SCHEMA ON CATALOG `test_catalog` TO `pandi.anbu@avatest.in`;
GRANT SELECT ON TABLE `test_catalog.bronze.address` TO `keyvault_user`;
GRANT SELECT ON TABLE `test_catalog.bronze.agreement` TO `keyvault_user`;
GRANT USE_SCHEMA ON SCHEMA `test_catalog.information_schema` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `test_catalog.information_schema.volumes` TO `account users`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON CATALOG `uc_test_catalog` TO `syed.hussain@avatest.in`;
GRANT BROWSE ON CATALOG `uc_test_catalog` TO `account users`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON CATALOG `uc_test_catalog` TO `naveenap@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON CATALOG `uc_test_catalog` TO `pandi.anbu@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON CATALOG `uc_test_catalog` TO `kevin.premjit@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON CATALOG `uc_test_catalog` TO `sabareeswaraks@avatest.in`;
GRANT SELECT ON TABLE `uc_test_catalog.bronze.categories` TO `keyvault_user`;
GRANT SELECT ON TABLE `uc_test_catalog.bronze.supplier` TO `keyvault_user`;
GRANT USE_SCHEMA ON SCHEMA `uc_test_catalog.information_schema` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `uc_test_catalog.information_schema.volumes` TO `account users`;
GRANT ALL_PRIVILEGES, MANAGE ON CATALOG `xanterra_poc` TO `deeraj.rajeev@avatest.in`;
GRANT BROWSE ON CATALOG `xanterra_poc` TO `account users`;
GRANT USE_CATALOG ON CATALOG `xanterra_poc` TO `dharun@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON CATALOG `xanterra_poc` TO `pandi.anbu@avatest.in`;
GRANT USE_CATALOG ON CATALOG `xanterra_poc` TO `kishore.n@avatest.in`;
GRANT ALL_PRIVILEGES ON CATALOG `xanterra_poc` TO `hariharan.m.a@avatest.in`;
GRANT ALL_PRIVILEGES ON CATALOG `xanterra_poc` TO `karthikeyan.devendhiran@avatest.in`;
GRANT APPLY_TAG, BROWSE, CREATE_FUNCTION, CREATE_MATERIALIZED_VIEW, CREATE_MODEL, CREATE_SCHEMA, CREATE_TABLE, CREATE_VOLUME, MODIFY, READ_VOLUME, SELECT, USE_CATALOG, USE_SCHEMA, WRITE_VOLUME ON CATALOG `xanterra_poc` TO `sukeshnd@avatest.in`;
GRANT USE_SCHEMA ON SCHEMA `xanterra_poc.bronze` TO `kishore.n@avatest.in`;
GRANT APPLY_TAG, CREATE_FUNCTION, CREATE_MATERIALIZED_VIEW, CREATE_MODEL, CREATE_TABLE, CREATE_VOLUME, EXTERNAL_USE_SCHEMA, MANAGE, MODIFY, READ_VOLUME, SELECT, USE_SCHEMA, WRITE_VOLUME ON SCHEMA `xanterra_poc.bronze` TO `dharun@avatest.in`;
GRANT ALL_PRIVILEGES, MANAGE ON TABLE `xanterra_poc.bronze.student_scores` TO `kishore.n@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON SCHEMA `xanterra_poc.default` TO `dharun@avatest.in`;
GRANT USE_SCHEMA ON SCHEMA `xanterra_poc.information_schema` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.catalog_privileges` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.catalog_tags` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.catalogs` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.check_constraints` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.column_masks` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.column_tags` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.columns` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.constraint_column_usage` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.constraint_table_usage` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.information_schema_catalog_name` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.key_column_usage` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.parameters` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.referential_constraints` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.routine_columns` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.routine_privileges` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.routines` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.row_filters` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.schema_privileges` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.schema_tags` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.schemata` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.table_constraints` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.table_privileges` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.table_tags` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.tables` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.views` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.volume_privileges` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.volume_tags` TO `account users`;
GRANT SELECT ON TABLE `xanterra_poc.information_schema.volumes` TO `account users`;
GRANT ALL_PRIVILEGES, MANAGE ON SCHEMA `xanterra_poc.mastermetadata` TO `dharun@avatest.in`;
GRANT ALL_PRIVILEGES, EXTERNAL_USE_SCHEMA, MANAGE ON SCHEMA `xanterra_poc.silver` TO `dharun@avatest.in`;
